Custom-Join-Message: true
MySQL:
  Host: null:null
  Database: null
  Username: null
  Password: null
Flirts:
- "I bet your name's Mickey, 'cause you're so fine."
- "Hey, pretty mama. You smell kinda pretty, wanna smell me?"
- "I better get out my library card, 'cause I'm checkin' you out."
- "If you were a booger, I'd pick you."
- "If I could rearrange the alphabet, I would put U and I together."
- "I've been bad, take me to your room."
- "I think Heaven's missing an angel."
- "Are you a parking ticket? Because you've got FINE written all over you."
- "That shirt looks good on you, it'd look better on my bedroom floor."
- "Can I have your phone number? I seem to have lost mine."
- "I cant help to notice but you look a lot like my next girlfriend."
- "Aren't your feet tired? Because you've been running through my mind all day."
- "I must be asleep, 'cause you are a dream come true."
- "How you doin'?"
- "If I said you had a good body, would you hold it against me?"
- "Hey, baby cakes."
- "Nice butt."
- "I love you like a fat kid loves cake."
- "Do you believe in love at first sight? Or should I walk by again...?"
- "Do you have a map? I think I just got lost in your eyes."
- "Want to see my good side? Hah, that was a trick question, all I have are good sides."
- "Now you're officially my woman. Kudos! I can't say I don't envy you."
- "I find that the most erotic part of a woman is the boobies."
- "I wish I was one of your tears, so I could be born in your eye, run down your cheek, and die on your lips."
- "It’s a good thing I wore my gloves today; otherwise, you’d be too hot to handle."
- "Lets say you and I knock some very /sensual/ boots."
- "I lost my phone number, can I have yours?"
- "Does this rag smell like chloroform to you? "
- "I'm here, where are your other two wishes?"
- "Apart from being sexy, what do you do for a living?"
- "Hi, I'm Mr. Right. Someone said you were looking for me."
- "You got something on your chest: My eyes."
- "Are you from Tennessee? Cause you're the only TEN I see."
- "Are you an alien? Because you just abducted my heart."
- "Excuse me, but I think you dropped something!!! MY JAW!!!"
- "If I followed you home, would you keep me?"
- "I wish you were a Pony Carousel outside Walmart, so I could ride you all day long for a quarter."
- "Where have you been all my life?"
- "I'm just a love machine, and I don't work for nobody but you."
- "Do you live on a chicken farm? Because you sure know how to raise cocks."
- "Are you wearing space pants? Because your ass is out of this world."
- "Nice legs. What time do they open?"
- "Are you lost? Because it’s so strange to see an angel so far from heaven."
- "Your body is a temple? Well, I'm Indiana Jones."
- "ay gurl r u a beaver? cuz dam"
- "You may not be Jesus, but I sure would nail the shit out of you ;)"
- "According to the multiverse theory, there are universes in which we are having sex right now.."
- "Are you studying evolutionary biology? 'Cause your phenotype makes me wanna spread my genotype."
- "Do you have any raisins? No? Well how about a date?"
- "Hey bbygurl, we should e^(4.234) rounded up to the nearest whole number ;)"
- "Are you wearing underwear? Oh well then my watch is fifteen minutes ahead."
- "Is your name Wi-fi? Because I'm really feeling a connection."
- "You make my software turn into hardware!"
- "Is your name Google? Because you have everything I've been searching for."
- "Come to my 127.0.0.1 and I’ll give you sudo access."
- "Computer techs have skilled fingers if you know what I mean."
- "If beauty were time, you'd be eternity."
- "Hey baby, you must be a light switch, cuz every time I see you, you turn me on!"
- "Is there an airport nearby or is that just my heart taking off?"
- "I must be a snowflake, because I've fallen for you."
- "There is something wrong with my cell phone. It doesn't have your number in it."
- "Kiss me if I'm wrong, but dinosaurs still exist, right?"
- "Are you going to kiss me or do I have to lie to my diary?"
- "Did the sun come out or did you just smile at me?"
- "If you were a tear in my eye I would not cry for fear of losing you."
- "Are you a magician??? Because Abraca-DAYUM!"
- "Are you a kidnapper? Because you just abducted my heart."
- "Can you pull this heart-shaped arrow out of my butt? A damn little kid with wings shot me."
- "Hey girl, if you were to get mauled by a bear with chainsaw hands, I hope he would stay away from your face, because I think you're cute!"
- "Your daddy must have been a baker, because you've got a nice set of buns."
- "Wanna dance? I can really put your inertia in motion."
- "What do you say we use my lever to shift your center of mass?"
- "If you were a Dementor, I'd become a criminal just to get your kiss."
- "No, that's not an iPod mini in my pocket. I'm just happy to see you."
- "Have you heard of Platform 9 and 3/4? Well, I can think of something else with the exact same measurements."
- "I heard you were in Gryffin-whore, because you let every wizard slyther-in."
YesMsgs:
- "As I see it, yes"
- "It is certain"
- "It is decidedly so"
- "Most likely"
- "Outlook good"
- "Signs point to yes"
- "One would be wise to think so"
- "Naturally"
- "Without a doubt"
- "Yes"
- "Yes, definitely"
- "You may rely on it"
NeutralMsgs:
- "Reply hazy, try again"
- "Ask again later"
- "Better not tell you now"
- "Cannot predict now"
- "Concentrate and ask again"
- "You know the answer better than I"
- "Maybe..."
NoMsgs:
- "You're kidding, right?"
- "Don't count on it"
- "In your dreams"
- "My reply is no"
- "My sources say no"
- "Outlook not so good"
- "Very doubtful"