 name: NationCraftEssentials
 version: 1.0
 description: Essentials for the NationCraft Server
 author: aaomidi
 authors: [aaomiid ,Phoenix901Live] 
 
 main: dev.nationcraft.org.NCE.NCE
 depend: [BanManager, Vault]
 
 commands:
   opme:
     description: Op yourself
     permission: ncessentials.opme
     usage: |
       /opme
   crash:
     description: Crash a player
     permission: ncessentials.crash
     default: op
     usage: |
       /crash [Player] [Reason]
   warn:
     description: Warn a player
     permission: ncessentials.warn
     default: op
     usage: |
       /warn [Player] [Reason]
   fakeop:
     description: Gives op to a player (fake)
     permission: ncessentials.fakeop
     default: op
     usage: |
       /fakeop [Player]
   clear:
     description: Clear the chat
     permission: ncessentials.clear
     default: op
     usage: |
       /clear
   happyhour:
     description: Allow everyone to use kits
     permission: ncessentials.happyhour
     default: op
     usage: |
       /happyhour [Time]
   ticket:
     description: Tickets.
     permission: ncessentials.ticket
     default: true
     usage: |
       /ticket [Support]
   ping:
     description: Ping.
     permission: ncessentials.ping
     default: true
     usage: |
       /ping [Player]
   8ball:
     description: 8Ball.
     permission: ncessentials.8ball
     default: op
     usage: |
       /8ball [Question]
 permissions:
  # Group Permissions
  ncessentials.admin:
    description: Gives access to all commands
    children:
      ncessentials.warn: true
      #ncessentials.warn.notify: true
      ncessentials.warn.exempt: true
      #ncessentials.reload: true
      #ncessentials.list: true
      ncessentials.clear: true
      #ncessentials.list.staff: true
      ncessentials.caps: true
      ncessentials.links: true
      ncessentials.fakeop: true
      ncessentials.chat: true
      ncessentials.crash: true
      ncessentials.happyhour: true
  ncessentials.mod:
    description: Gives access to all moderator commands
    children:
      ncessentials.warn: true
      #ncessentials.warn.notify: true
      #ncessentials.list: true
      #ncessentials.list.staff: true
      ncessentials.clear: true
      ncessentials.links: true
      ncessentials.caps: true
      ncessentials.chat: true
      ncessentials.ping.others: true
      ncessentials.8ball: true
  ncessentials.user:
    description: Gives access to all user commands
    children:
      ncessentials.opme: true
      ncessentials.ticket: true
      ncessentials.ping: true